enum ActionKind {
    Walking,
    Idle,
    Jumping,
    Casting
}
namespace SpriteKind {
    export const Spell = SpriteKind.create()
    export const FinalBoss = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Spell, SpriteKind.Player, function (sprite, otherSprite) {
    sprite.destroy()
    info.changeLifeBy(-1)
})
function Set_MySprite () {
    mySprite = sprites.create(img`
        .....c.cc.....
        ....cfcff.c...
        ...ffffeffc...
        ..cfcfedbefc..
        ...feecefefc..
        ..cffefeeffc..
        ...fffbebbc...
        ...cfceddbb...
        ....fcbbbbe...
        ...ccfbbbbe...
        ..cfefeeec....
        .cffbbe1ec....
        ..ccccfceec...
        ..ccffecc2c...
        ..ccffecc2c...
        ..cfbeecc2fc..
        ...edbecc2eb..
        ....cceeeeb...
        ....ffffff....
        ....fcffcce...
        ...ffcefccc...
        ..cfccefccc...
        ..ccccefcf....
        ..ccbcefffc...
        .cccbceffcc...
        .beccceffccc..
        .ccfeeeffcfcc.
        ccfffffcbcffcc
        ccffffffffffc.
        .fcffffffffcc.
        ..cccffcfccc..
        ..c.cccfcc....
        `, SpriteKind.Player)
    mySprite.setPosition(0, 50)
    controller.moveSprite(mySprite, 0, 100)
    mySprite.setStayInScreen(true)
}
sprites.onDestroyed(SpriteKind.FinalBoss, function (sprite) {
    pause(1000)
    game.showLongText("You defeated Voldemort's army. Hogwarts is safe. ", DialogLayout.Full)
    pause(1000)
    game.setDialogTextColor(5)
    game.over(true, effects.confetti)
})
function Set_Spell () {
    HarryPotter2 = img`
        .............
        ....cc.c.....
        ...cffffcc...
        .ccfcfecffc..
        ..ffefdbeec..
        ..feeffcffc..
        .cfffebeffc..
        ..cfcbbbbc...
        ..ffebdbbe...
        ...cbbbeecc..
        .ceffbbbee...
        .ccbeeecc....
        .cccebecfc...
        .cccbdeeccc..
        .cffcbeeccc..
        ..cffebecfc..
        ...ff2bcbbc..
        ...cc2ccbe...
        ..ccceffe....
        ..ccceffe....
        ..ccc2fcce...
        .cfcc2fcce...
        .cfcc2ccc....
        .ccbc2ccc....
        .fcbc2cff....
        .ecbc2cfcfc..
        .feecefffcc..
        fcff2ffcffcf.
        cffffffcfffc.
        cffffffffffcc
        ccfcffffcfcc.
        .ccffccffcc..
        ...cccccc....
        .............
        `
    HarryPotter3 = img`
        .....c.cc....
        ....cccffc.c.
        ...ffefecff..
        ..cffecbbefc.
        ...ffecefcfc.
        ..cffefcecfc.
        ...ffeceebc..
        ...cbdebdbb..
        ..cbcbbbbbe..
        ..cccffbbbe..
        ..ccc2eecc...
        ..cff2eb2cc..
        ..cff2cc2fcc.
        ...fcecb2bec.
        ...ccccb2bcc.
        ...ceccb2....
        ..ccecccce...
        ..cceccffe...
        ..ccecccce...
        ..fcecccceb..
        ..fbecbcbe...
        .fcbeccccc...
        .fcbeccccc...
        ceececccfcc..
        .ce2eccffbc..
        ccffffffffcc.
        cfffffcbfffcf
        cfffffffffffc
        ccfffffffffcc
        .cccffffcccc.
        ...cccccf.c..
        `
    HarryPotter4 = img`
        ........c.cc...
        .......ffcfccc.
        .....cfffcffff.
        ec...ffcfbbfffc
        eec..cfceeefffc
        ceec.cccffceec.
        .cebbcfffceeec.
        ..cbbcffceedbe.
        ..ccccffbbbbbe.
        ...ccccfbbbbe..
        ...ccffebeeec..
        ....cfffeecc...
        ....cffcecbec..
        .....cfceceec..
        .....cfcebccc..
        .....fcecbe....
        ....cfcecb2....
        ....fccecce....
        ...ccccefcce...
        ...ccccecccc...
        ...fccecccbc...
        ..ccbc2ccccc...
        ..fcbc2ccccf...
        .ceecc2ccfcc...
        ..cfececffccc..
        ..cff2fffffccc.
        .ccfffffccfffcc
        ..ffffffffffff6
        .cccffffffffccc
        ...ffcffffcff..
        ...cccccccccc..
        .......cc......
        `
    HarryPotter5 = img`
        ..............
        .......c.cc...
        .....ccfffccc.
        ....cfffcecfc.
        ....ffefebeefc
        ccc.ccceefcff.
        eeccffffffebfc
        cceeeecffbebe.
        ...cedbebbbbbc
        ....cbccbbbec.
        ....ccfebbbc..
        ...cfcffbccc..
        ..cefff2e2c...
        ...cfff2e2c...
        ....ffc2c2c...
        ....cfc2c2c...
        ....fcecc2c...
        ....ccebc2bb..
        ...fccecf2b...
        ..cccceffe....
        ..ccccefcc....
        .cfcccefcf....
        .fcbc2cfcf....
        ccbbc2cff.....
        fcbcc2cffc....
        ceccefcfccc...
        .f2cffffffcc..
        ccffffccfffcc.
        ffffffffffff..
        ccfffffffffcc.
        .ffcffffcfcc..
        ..ccccccc.c...
        .....c..c.....
        `
    HarryPotter6 = img`
        ....................
        ........c.c.........
        ......cffffcc.......
        .....cfffeeff.......
        ....cffefdecef......
        .....fceeefffc......
        ....cfffffcbef......
        .....ffffcebe.......
        .....cffebbdbc......
        ......cfebbbe.......
        ......eeebbbc.......
        ....cbeffcccddeccccc
        ...ceeffccbcbeeeeeec
        ...fbcfcccffee......
        ..cffffffecc........
        ..ccffffef..........
        ...ccfcfe...........
        ....cccff...........
        ....cccff...........
        ....cccef...........
        ...fccf2f...........
        ..ccccecf...........
        ..cccceff...........
        .cccccefc...........
        .cbcccefcfc.........
        ceccc2ffccc.........
        ffe22fcfffcf........
        cfffffccfffcc.......
        cffffffffffcc.......
        ccffffffffcc........
        .ccffccfccc.........
        `
}
function Make_Voldemort () {
    if (!(BossSpawn) && (Message_spawn == true && info.score() == 200)) {
        BossSpawn = true
        Message_spawn = false
        for (let value of sprites.allOfKind(SpriteKind.Enemy)) {
            value.destroy()
        }
        music.spooky.play()
        game.showLongText("He, who must not be named, is here!", DialogLayout.Bottom)
        Voldemort = sprites.create(img`
            .........................................
            .........................................
            .........................................
            ..................cb111c.................
            ..................ddd11d.................
            .................dbbd11db................
            .................dbdd11db................
            .................cbdddddb................
            .................ccdbb1b.................
            ..................b1dd1b.................
            ..................bd11de.................
            ..................cbbd...................
            ................fffcbcdefff..............
            ................fffcddfffff..............
            ...............ffffbdccccff..............
            ...............ffffbcccfcf3f.............
            ...............fffffcfffffffff...........
            ...............fffffcfffffffff...........
            ...............ffffcfffffffffff..........
            ...............fffccffffffffffff.........
            ...............fffcccfffffcffffff........
            ...............fffffcffffffcfffff........
            ...............cfcfffcfffffffffff........
            ..............dddcfffcffffdd6ffff........
            .............cddcfffffcff6bd6fffff.......
            .............ffdffffffff6bbbfffffff......
            ..............ffffffff6666ffffffffff.....
            ..............fffffff666fcffffffffff.....
            ..............fffffff6ffffccffffffff.....
            ..............ffcfffffffcffcccffffff.....
            ..............ffccfffffccffffcccffff.....
            .............ffcfffffffcfcfffffcccff.....
            .............ffffffffffffcff.....ccf.....
            .............ffffffffffffcff.............
            .............fcfffffffffcfff.............
            .............fffffffffffcfff.............
            .............fddcdcffffffffff............
            .........................ddcf............
            .........................................
            `, SpriteKind.FinalBoss)
        Voldemort.setPosition(100, 50)
        Voldemort.setVelocity(randint(0, 100), randint(0, 100))
        Voldemort.setStayInScreen(true)
        Voldemort.setBounceOnWall(true)
        statusbar = statusbars.create(20, 4, StatusBarKind.EnemyHealth)
        statusbar.attachToSprite(Voldemort, -45, 0)
        statusbars.getStatusBarAttachedTo(StatusBarKind.EnemyHealth, Voldemort).max = 70
        statusbar.setColor(2, 15)
    }
}
sprites.onOverlap(SpriteKind.FinalBoss, SpriteKind.Player, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    pause(100)
    Voldemort.x += 125
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Dead == false) {
        projectile = sprites.createProjectileFromSprite(img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ...........3............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `, mySprite, 100, 0)
        projectile.startEffect(effects.starField)
        animation.runImageAnimation(
        mySprite,
        [HarryPotter2, HarryPotter3, HarryPotter4, HarryPotter5, HarryPotter6],
        70,
        false
        )
        animation.runImageAnimation(
        projectile,
        [CastSpell1, CastSpell2, CastSpell3, CastSpell4],
        150,
        false
        )
    }
})
function Set_HP () {
    CastSpell1 = img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........999...........
        ........9119............
        .......91119............
        .......9119.............
        ........9...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `
    CastSpell2 = img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .......9999.............
        .......99999............
        ...........99999........
        ...........911199.......
        ........991111199.......
        .......991111119........
        .......91199999.........
        .......99999999.........
        ...........999..........
        .........999............
        .......999..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `
    CastSpell3 = img`
        ........................
        ........................
        ........................
        ........................
        ........................
        .......99...............
        .......9999.............
        .......99999............
        .......9919999..99......
        .......999911999999.....
        .......11dd91111199.....
        .......111111d11199.....
        .......111111d1119......
        .......99999199999......
        .......9.9999.999.......
        .......9.9199...........
        .......99999............
        .......19...............
        .......99...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `
    CastSpell4 = img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        .......9................
        ........999.............
        ........9999............
        ........9...99..........
        ........9...99..........
        .......9.....99.........
        .......9...99999........
        .........99..911........
        .......99..91111........
        ...........99919........
        .............999........
        .......9...999..........
        .........9..99..........
        ........99..9...........
        ........9..9............
        .......9................
        .......9................
        ........................
        ........................
        `
}
info.onLifeZero(function () {
    if (Message_spawn == true) {
        Dead = true
        mySprite.destroy()
        for (let value of sprites.allOfKind(SpriteKind.Enemy)) {
            value.destroy()
        }
        for (let value of sprites.allOfKind(SpriteKind.Projectile)) {
            value.destroy()
        }
        Voldemort = sprites.create(img`
            .........................................
            .........................................
            .........................................
            ..................cb111c.................
            ..................ddd11d.................
            .................dbbd11db................
            .................dbdd11db................
            .................cbdddddb................
            .................ccdbb1b.................
            ..................b1dd1b.................
            ..................bd11de.................
            ..................cbbd...................
            ................fffcbcdefff..............
            ................fffcddfffff..............
            ...............ffffbdccccff..............
            ...............ffffbcccfcf3f.............
            ...............fffffcfffffffff...........
            ...............fffffcfffffffff...........
            ...............ffffcfffffffffff..........
            ...............fffccffffffffffff.........
            ...............fffcccfffffcffffff........
            ...............fffffcffffffcfffff........
            ...............cfcfffcfffffffffff........
            ..............dddcfffcffffdd6ffff........
            .............cddcfffffcff6bd6fffff.......
            .............ffdffffffff6bbbfffffff......
            ..............ffffffff6666ffffffffff.....
            ..............fffffff666fcffffffffff.....
            ..............fffffff6ffffccffffffff.....
            ..............ffcfffffffcffcccffffff.....
            ..............ffccfffffccffffcccffff.....
            .............ffcfffffffcfcfffffcccff.....
            .............ffffffffffffcff.....ccf.....
            .............ffffffffffffcff.............
            .............fcfffffffffcfff.............
            .............fffffffffffcfff.............
            .............fddcdcffffffffff............
            .........................ddcf............
            .........................................
            `, SpriteKind.FinalBoss)
        Voldemort.setPosition(100, 50)
        Voldemort.say("HARRY POTTER IS DEAD!! HAHAHAHAHA")
        timer.after(3500, function () {
            game.over(false, effects.melt)
            game.reset()
        })
    } else if (Message_spawn == false) {
        Dead = true
        mySprite.destroy()
        animation.stopAnimation(animation.AnimationTypes.All, mySprite)
        animation.stopAnimation(animation.AnimationTypes.All, projectile)
        for (let value of sprites.allOfKind(SpriteKind.Projectile)) {
            value.destroy()
        }
        Voldemort.say("HARRY POTTER IS DEAD!! HAHAHAHAHA")
        timer.after(3500, function () {
            game.over(false, effects.melt)
            game.reset()
        })
    }
})
sprites.onDestroyed(SpriteKind.Enemy, function (sprite) {
    Fired = true
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.FinalBoss, function (sprite, otherSprite) {
    sprite.destroy()
    music.pewPew.play()
    statusbars.getStatusBarAttachedTo(StatusBarKind.EnemyHealth, otherSprite).value += -10
    if (statusbars.getStatusBarAttachedTo(StatusBarKind.EnemyHealth, Voldemort).value == 0) {
        Voldemort.destroy(effects.ashes, 500)
    }
})
function MakeBellatrix () {
    if (Message_spawn == true && !(BossSpawn)) {
        Bellatrix = sprites.createProjectileFromSide(img`
            .........999999d.....
            ......dbccc9999ddd...
            ......bccccccbbdcbd..
            ......bccccccbdddcb..
            .....dccccdcccdcfcb..
            .....bcccdddcccccb...
            .....beccdddccccb....
            .....bcccdddfffcd....
            d....bcccdddcccb.....
            bddddcccccdcccccd....
            ddbcccffccccffccb....
            dbbcccfffffffccbd....
            ddbbdbccccfcccbb.....
            .....dbcccffcbd......
            ......dbccfffb.......
            .......dcffffcd......
            .......dcffffcb......
            .......bffffccc......
            ......dcffffffcd.....
            ......bcffffffcd.....
            ......bcffffffcb.....
            .....dcfffffffcb.....
            .....bcfffffffcb.....
            .....bcffffffffcd....
            ....dcfffffffffcd....
            ....bcfffffffffcd....
            ....bffcccffffccd....
            ....cfcccccccfcc.....
            ...dccb...ddbccd.....
            ...dccd.....dccb.....
            ...dccd.....dbccb....
            ...bffb......bffb....
            `, 0, -50)
        Bellatrix.x = randint(51, 155)
        Bellatrix.setKind(SpriteKind.Enemy)
        ProjectileFireTime = game.runtime() + randint(1000, 3000)
        Fired = false
    }
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprite.destroy()
    otherSprite.destroy(effects.fire, 200)
    music.pewPew.play()
    info.changeScoreBy(10)
    if (info.score() == 100) {
        info.changeLifeBy(1)
        music.beamUp.play()
    } else if (info.score() == 200) {
        info.changeLifeBy(1)
        music.beamUp.play()
    } else if (info.score() == 300) {
        info.changeLifeBy(1)
        music.beamUp.play()
    } else if (info.score() == 400) {
        info.changeLifeBy(1)
        music.beamUp.play()
    } else if (info.score() == 500) {
        info.changeLifeBy(1)
        music.beamUp.play()
    }
    Make_Voldemort()
})
let MyEnemy_1: Sprite = null
let Bellatrix_Spell: Sprite = null
let Voldemort_Spell: Sprite = null
let Voldemort_Fired = false
let Voldemort_Fire_TIme = 0
let ProjectileFireTime = 0
let Bellatrix: Sprite = null
let Fired = false
let CastSpell4: Image = null
let CastSpell3: Image = null
let CastSpell2: Image = null
let CastSpell1: Image = null
let projectile: Sprite = null
let statusbar: StatusBarSprite = null
let Voldemort: Sprite = null
let HarryPotter6: Image = null
let HarryPotter5: Image = null
let HarryPotter4: Image = null
let HarryPotter3: Image = null
let HarryPotter2: Image = null
let mySprite: Sprite = null
let Dead = false
let Message_spawn = false
let BossSpawn = false
scene.setBackgroundImage(img`
    fffffffcbccffffffffffcfbddddddddddd111111111111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbffcddffffffcfcfffff
    fffffffccffffcffffffbfddddddddd11111111111111111111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfccdbffffffffffffff
    fffffffcffffffbffffffddddddddd1111111111111111111111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcffcbfffffffffffcdcf
    ffffffcffffffffbdffffddddddd11111111111111111111111111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddccffffffdfbfffffff
    fcfffffffcdcdffdffdccdddddd11111111111111111111111111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbffffffdffffffff
    fffffffffdbddcfffffcddddd1111111111111111111111111111111111111111111dddd1dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcfcfffffcfffbfff
    fcffffbffbffffffffbbddddd111111111111111111111111111111111111111111d11dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbdcfffffffffbffff
    fcbffffffcfffffffcdddd1111111111111111111111111111111111111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddccffffffffffffff
    fdcccffffdbffcffccdddd111111111111111111cc1111111111111111111111111d111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcfffffffffffffff
    fffffffffffffffcdddd1111111111111111111cccc111111111111111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfcfffffffffffff
    ffffffffffffffcbddd11111111111111111111cccc11111111111111111111111111111dddd1ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcffffffffffffff
    fffffffddcfffdddddd11111111111111111111ccccc11111111111111111111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffffff
    fffffffdddbffbddd111111111111111111111cccccc111111111111111111111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbcfffcffffffffff
    ffffffcbfcccddddd111111111111111111111ccccccc11111111111111111111111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddccfffffffffffff
    fffffffffcfddddd1111111111111111111111ccccccc11111111111111111111111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcffffffffffff
    ffffffffdfcdddd1111111d11111d111111111cccccccc11111111111111111111111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcfbfffcfffffff
    ffffffffcfbddd11111111111111111111111ccccccccc1111111111111111111111111111111111d1dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbfffdffffffff
    fffffffcdcdddd11111111111111111111111cccccccccc1111111ccc111111111ccc111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffffffff
    fffffbfffcddd11111111111111111111111ccccccccccc1111111cccc111c1111ccc11111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbcffffffffffff
    fccffdcbfbddd11111111111111111111111cccccccccccc111111cccc11ccc111ccc1111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbcffffffffffff
    fffcffcdfbdd11111111111111111111111ccccccccccccccc1111cc1c11ccc11cccc111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbcffffffffffff
    ffddfffbbbdd1111111111111111111111cccccccccccccccc1111cc1c11ccc11c11c111111111111111dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcfccfffffffff
    cfdffffbcdd11111111111111111111111cccccccccccccccc1111ccccccccccccccc1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbfcdfffffffff
    ffffffccdd111111111111111111111111cccccccccccccccc1111ccccccccccccccc1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddccfbfffffffff
    ffcfffbdb111111111111111111111111111cccccccccccc111111ccccccccccccccc1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddbbdddddddddddddddcfdbffffffff
    fffffcddddd1111111111111111111111111cc1cc1ccd1cc111111ccccccccccccccc1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddbddddddddddddddddbfcfffffffff
    fffffbdddd11111111111111111111111111cc1cc1ccc1cc1111111ccccccccccccc1111111111111111ddddddddddddddddddddddddddddddddddddddddddddddbbddddddddddddddddcfcfffffffff
    ffffcbddddd1111111111111111111111111cccccccccccc11111111ccccccccccc11111111111111111d1ddddddddddddddddddddddddddddddddddddddddddddbddddddddddddddddbcfffffffffff
    fffccddddd11111111111111111111111111cccccccccccc111111111cccccccccc11111111111111111ddddddddddddddddddddddddddddddddddddddddddddddbdddddddddddddddbbffffffffffff
    ffdcbddddd11111111111111111111111111cccccccccccc111111111ccccccccc111111111111111111ddddddddddddddddddddddddddddddddddddddddddddddbddddddddddddddddbffffffffffcf
    ffccddddddd11111111111111111111111111cccccccccc1111111111ccccccccc1111111111111111111dddddddddddddddddddddddddddddddddddddddddddddbddddddbbdddddddbcffffffffffff
    ffcbdddddd1111111111111111111111111111cccccccc11b11111111ccccccccc111111111111bb1111ddddddddddddddddddddddddddddddddddddddddddbbddbbdddddbbdddddddbccfffffffffff
    ffcbddddd111111111111111111111111111111cccccccbccccccc111ccccccccc1111111111111b1111dddddddddddddddddddddddddddddddddddddddddddbbddbddddddbddddddddfffffffffffff
    fcbbdddddd1111111111cccb1ccc1111cccc111ccccccccccccccccc1ccccccccc1111111111111b1111dddddddddddddddddddddddddddddddddddddddddddbbbdbbdddddbdbddddbbbcfffffffffff
    fcddddddd1111111111ccccb1cccc11ccccc111cccccccccbbccbbbccccccccccc1111111111111b111ddddddddddddddddddddddddddbdddddddddddddddddddbddbbddddbbbddbbbcfffffffffffff
    ccddddddd1111111111cccccbcccc11ccccc111cccccccccbbcccbbccccccccccc111111111111111111dddddddddddddddddddddddddbbdddddddddddddddddddbddbddddbbddbbbbffffffffffffff
    ddddddddd1111111111ccc1ccccccccc1ccc111ccccccccccccccccccccccccccc1111111111111b111bdddddddddddddddddddddddddbbdddddddddddddddddddbbbbddddbddbbbbccfffffffffffff
    dddddddd11111111111cc11ccc11cccc1ccc111ccccccccc1111cccccccccccccc1111111111111b111bddd1dddddddddddddddddddddbdddbdddddddddddddddddbbbddddbbbbbbbccfffffffffffff
    dddddddd11111111111cccccccbcccccccccc11cccccccc1111111cccccccccccc1111111111111b111bddd1dddddddddddddddddddddbddbbdddddddddddddddddbbbdddbbbbbbbbccfffffffffffff
    dddddddd11111111111ccccccccccccccccc111ccccccc1111b1111ccccccccccc1111111111111b1dbb1ddddddddddddddbbbbddddddbddbdddddddddddddddddddbbdddbbbbbbbccffffffffffffff
    dddddddddd111111111cccccccccccccccc1bb1ccccccc1111bb111ccccccccccc11111b1111111b1dbbdddddddddddddddbddbbbddddbdbddddddddddddddddddddbbddbbbbbbbbcbffffffffffffff
    dddddddddd1111111111cccccccccccccccccccccccccc111111111cccccccccccbb11111111111b1db1dddddddddddddddbdddbbddddbbdddddddddddddddddddddbbdbbbbbbbbccfffffffffffffff
    dddddddddd11111111111cccccccccccccbccbbccccccc1111111b1cccccccccccbbbb111111111b1db1ddd1ddddddddddbbdddbbbddbbdddddddddddbbddddddddbbbbbbbbbbbcbbcffffffffffffff
    ddddddddd1d11111111111ccccccccccccbbcbbccccccc1111111b1cccccccccccc1b1111111111bbbddddd1dddddddddbbdddddbbdbbddddddddddddbdddddddddbbbbbbbbbbccbcfffffffffffffff
    ddddddddd1d11b11111111ccccccccccccbccbcccccccc111111bb1cccccccccccc111111111111bbbdddddddddddddddbbdddddbbbbbddddddddddddbdddddddddbbbbbbbbbbbbcffffffffffffffff
    ddddddddd1d11b11111111cccccccccccccccccccccccc1111111bbcccccccccccc11111111111bbbdddddddddddddddddddddddbbbbddddddddddddbbdddddbddbbbbbbbbbbbccfffffffffffffffff
    dddddddddddddbbd1bb111cccccccccccc111d1cccccccd1d1111bbcccccccccccc11111111111bbb1ddddddddddddddddddddddbbbbddddddddddddbbdddddbddbbbbbbbbbbbbccffffffffffffffff
    dddddddddddddbbd1b1111ccccccccccccddbccccccccccc1ddddbccccccccccccc11111111bb1bb11dddbddddddddddddddddddbbbbddddddddddddbbdddddbdbbbbbbbbbbbbcffffffffffffffffff
    ddddddddddddddbd1b11bbccccccccccccccccccccccccccbcccccccccccccccccb1d111111bbbbbdddddbbdddddddddddddddddbbbbddddddddddddbbdddddbdbbbbbbbbbbbbcffffffffffffffffff
    ddddddddddddddbb1b11bbccccccccccccccccccccccccccccccccccccccccccccd1111b1111bbb11ddddbbdddddddddddddddddbbbbddddddddddddbbdddddbbbbbbbbbbbbbbcffffffffffffffffff
    dddddddddddddddb1b1db1ccccccccccccccccccccccccccccccccccccccccccccc1111d1111bbb11dddddbbddddddddddddddddbbbbbddddddddddddbdddddbbbbbbbbbbbbbbbcfffffffffffffffff
    ddddddddddddddddbb1bbdccccccccccccccccccccccccccccccccccccccccccccb1111d1111bbbddddddddbddddddddddddddddbbbbbddddddddddddbbdddbbbbbbbbbbbbbbbcffffffffffffffffff
    ddddddddddddddddbb1bbdccccccccccccccccccccccccccccccccccccccccccccb1b11d1111bbbddddddddbbdbbddddddddddddbbbbbddddddddddddbbddbbbbbbbbbbbbbbbcfcffffffffffffffcff
    ddddddddddddddddbb1b11cccccccccccccccccccccccccccccccccccccccccccccbbb111111bbbddddddddbbdbdddddddbbddddbbbbbdddddddddddbbbbbbbbbbbbbbbbbbbccfffffffffffffffffff
    ddddddddddddddddbddbd1ccccccccccccccccccccccccccccccccccccccccccccbbb111d111bbbb1dddddddbbbdddddddbbddddbbbbbddddddddbdbbbbbbbbbbbbbbbbbbbbcfcffffffffffffffffff
    ddddddddddddddddbbb111cccccccccccccccccccccccccccccccccccccccccccc1bb1111111bbbbddddddddbbbdddddddbdddddbbbbbddddbdddbdbbbbbbbbbbbbbbbbbbbbffffffffffffffffffcff
    ddddddddddddddddbbd111ccccccccccccccccccccccccccccccccccccccccccccd1bbb11111bbbbdddddddddbbddddddbbdddddbbbbbdddbbdddbbbbbbbbdbbbbbbbbbbbbcfffffffffffffffffffff
    ddddddddddddddddbbdd1dcccccccccccccccccccccccccccccccccccccccccccc111bb11111bbbbdddd1ddddbbddddddbbdddddbbbbbdddbbddddddbdddddddddbbbbbbbbcfffffffcfffffffffffff
    dddddddbbdddddbbbbddddcccccccccccccccccccccccccccccccccccccccccccc111bb1111bbbbbdddddddddbbbdddddbbdddddbbbbbddddbdbdddddddddddddddddddddddfffffffffffffffffffff
    dbddddddddbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccbcccccb11bb1111bbbbbdddddddddbbbdddddbbdddddbbbbbbdddddddddddddddbddddddddddbbcfffffffffffffffffffff
    ddbddbddbbbbbbbbbbbbbbcccccccccccccccccccccccccccccbccccccccccccccd11b11111bbbbbbddddddddbbbdddddbbddddbbbbbbdddddddddddddddddddddddddddbcffffffffffffffffffffff
    dbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccc111bb111bbbbbbbbdddddddbbbbddddbbdddbbbbbbddddddddddddddddddddddddddbbbcdfffffffffffffffffffff
    bbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccbb1bb1bbbbbbbbbbbbdddddbbbbddddbbddbbbbddbbdddddddddddddddddddbddddbccfddfffffffffffffffffffff
    dbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddddddddbdddddddddddddbcffffffffffffffffffffffffff
    bbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbdbddddbdddddddddddddddddddddddddddccffffffffffffffffffffffffff
    bbbbbbbbddbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbddddddddddbddddddddddddddddddddddbdddddbbbffbdfffffffffffffffffffffff
    bbbbbbbdddddbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbddddbddddddddbdddddddddddddddddddddddddddbddfcbfdffffffffffffffffffffff
    bbbbddddddddddddddbbbbcccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbdddddddddddddddddddddddddddddddddddddddddddddddddbdffdffbcfffffffffffffffffffff
    bbbddddddddddddbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccbbbdbbdbdddddddbddddbddddddddddddddddddddddddddddddddddddddcffcdfffffffffffffffffcfffffff
    bbdddddddddddddbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccbcccbbbbbddbdddddddddddddddddddddddddddddddddddddddddddddddddbcdffdfcdfffffffffffffffffffffff
    bddddddddddddddbdbbbbccccccccccccccccccccccccccccccccccccccccccbcbbbcbddddddddddddbddddddddddddddddddddddddddddddddddbddddddddddbfcffffcffffffffffffffffffffffff
    ddddddddddddddddbdbbbcccccccccccccccccccccccccccccccccccccccccbbcddddcdbddddbbddddbbdddddddddddbdddddddddddddddddddbddddddddddddcbdffffffffffbfffffcffffffffcbff
    dbdbddddddddbdbdbbbbccccccccccccccccccccccccccccccccccbcccbcbbdbcddddddddddddddddddddddddbddddddddddddddddddddddddddddddddddddddcffffffffffffffffffffffffcfffddf
    ddddddbddddddddbbbbbcccccccccccccccccccccccccccccccbbcbccbbbbdbdddddddddddbbbddddddddddddddddddddddddddddddddddddddddddddddddddbffffffffffffffffffffffffcdfffcff
    ddddddddddddbdbbbbbbccccccccccccccccccccccccccccccbbbbbbdddddddbddddddddddddbddddddddddddddddddddddddddddddddddddddddddddddddddcfffffffffffffffffffffffffffdffff
    dddddddddddddbbbbbbcccccccccccccccccccccccccccccbbbcddddbdbcdddcddddddddddddddddbdddbddddddddddbdddddddddddddddddddddddddddddddccfffffffffffffffffffffffffffffff
    ddddddddddddbbbbbbbcccccccccccccccccccccccccccbbddddddddbdbddddbdddddddddddddddddddddddddbbbddddddddddddddddddddddddddddddddddcfcffffffffffffffffcffffffffffffff
    bdbddddddbddbbbbbbccccccccccccccccccccccccccbddddbbdddddddddddddddddddbddddddddddddddddddddddddddddbdbdddddddddddddddddddddddbffffffffcffffffffffffffffcfcffffff
    dbddbdddddddbbbbcccccccccccccccccccccccccccdbdbdddddddddddddddddddddddbddddddddbdcbddddddddddddddddddddddddddddddddddddddddddcfffffffffffffffffffffffffffcffffff
    dddddddddddddddddbcbcccccccccccccccccccccbddcbbcdddbddddddddddddcdbddddddddddddddddddddbdddddddddddddddddddddddddddddddddddddfffbffffffffffffffffffffffffffcffff
    ddddddddddddcddddddbbccccccccccccccccbcbcbddddddbdbcddddddddddddddddddddddddddcbddddddddddddbdddddddddddddddddddddddddddddddcfffdfffffffffffffffffffffffffffffff
    dddddddddddbcdddddbddcbbcccccccbcccbbbbbccddbddddbdbdddddddddddddddddddddddddddddddddddddddddddddddddddddddbbddddddddddddddbffffcfffffffffffffffffffffffffffffff
    bdddddddddcdddddddddbcbbbcbbbcbbbdddbddddbddddddddddddddddbddddddddddddddddbcdddcddddddddddddddddddddddddddccddddddddddddddbddfffffffffffcffffffffffffffffcccfff
    ddddddddddddbddddbdddbbdbcbddbdbddddddddddbdddddddbdddddcddddddddddddbddddddddddddddddbddddddddbdddddddddddddddddddddddddddcdfffffffffffffffffffffffffffffccfffc
    dddcdddddddddddddddddcdddddddbdbbbdddbddddddddddddccdddddbddddddddcddddddddcddddddddddddddddddddddddddddddddddddddddcddddddcffffffffffffffffffffffffffffffffffff
    dddbdddddddddddddddddcdddddddcbddddbbddddddcdbddbdddddddddddbcbbbdcbddddddcbddddddddddddddddddddddddddddbddddddddddddddddddcfffffffffffffffcffffffffffffffffffff
    bdddddddddddddddddddddddddddbddbdbcbdbbddddbdddddddddddddbbbbbbcbbbbcdbbddddbddbcddddddddddddddddbdddddddddddddddddddddddddcffffbdcffffffffcffffffffffcfffffffff
    dddddddddddddddddddddddddddbbdddddbcdddddddbddddcdbbdbbbbcccbbccccbcbcbbbbbbbbccbcbbbdbbbbddddddddddddddddddddddddddbbbbdddcffffcfbfffffffffffffffffffffffffffff
    dddddddddddddddddddbdddddcbbddddddbbdddddddbbddddbbbbbccccccccccccccccccccccccccccbccbcbbccbdbbdddddddddddddddddddbbbbbbddbccfddfffffffffffbbfffffffffffffffffff
    bbbdddddddbddddddddddddbddcddbdddddbbddbccbcccbbcbbbcbccccccccccccccccccccccccccbcccccccccccccbbbdddddddddddddbbbbccccbbddccfffffcffffffffffffffffffffffffffffff
    cccbddddddddddddddddddddddbdddddbbbcbcccccbcccccccccccccccccccccccccccccccccccccccccccccccccccbccccbdbdddbdbbbcccbccbbbdddbfffffdfffffffffffffffffffffffffffffff
    ccccddbdddddddddddcddddccbbbccbbcbbccccccbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccbdddddfffffffffffffffcfffffffffffffffffffff
    ccbbbbbddddddddddbcdddcccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccccccccbbddddddbfffffffffffffffffffffffffffffffffffff
    ccccccbcbbbdddddbcccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbddddddddbfffffffffffffffffffffffffffffffffffff
    cccccccbccbbbcbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcbdddddddddbcffffffffffffffffcbfffffffffffffffffff
    cccccccccccbcbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccbbdddddbdddbcfffffffffffffffffffffffffffffffffffff
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcbbcccccccccccccbbbbddddddddddbcffcffffffffffffffffffffffffffffffffff
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccbbcccccbbcccccccbbbbdddddddddddbccffffffffffffffffffffffffffffffffffff
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcbddddddbbcbbbdbccccbbdddddbdddddddddcffdffdffffffffffffffffffffffffffffffff
    cccccccccccccccccccccccccccccccbbccccccccccccccccccccccccccccccccccccccccbcccbbbbbbddddddddddddddbbbbbbdddddcdddddddddddbcfffffffffffffffffffffffffffffffffffffc
    cccccccccccccccccccccccccccccbbddcbccccbccccccccccccccccccccccccccccccbdbbbbddddbdddddbddddddddddddddddddddddccdddddddddcfffffffffffffffffffffffffffffffffffffff
    cccccccccccccccccccccccccccbbbcddbbcbbbbbccbbcccccccccccccccccccccbbbddddbbdddddbdccddbdddddddddddddddddddddddddddddddbcffffffffffffffffffffcfffffffffffffffffff
    ccccccccccccccccccccccccccbddddddbbbbddbbbbdbccccccccccccccccccbcddddddddddbddcbdccbddddddddddddddddddddddddddddddddcbfdffffffffffffffffffffffffffffffffffffffff
    cccccccccccccccbccccccccbcdddddddddbddddddbbbddbbbbccccccccccccdbdddddddddddbddddddddddddddddddddddddddddddddddddddcfcfffffffffffffffffcbffffffffffffffcffffffff
    cccccccccccccccccccccfccccbddddddddddddddbcbcdddddbbbcccccbbbcdddddddbdddddddddddddddddddddddddddddddddddddddddddcdffbffffffffffffffffffbffffffffffffcbcffffffff
    ccccccccccccccccccfccffffccbdddddddddddddddbdbddddddcdbcbdddddddddddddddddddddddddddddddddddddddddddddddddddddddbcfffdffcfffffbfffffffffdccfffffffffffffffffffff
    cccccccccccccccffcffcccffffccdddddddddddddcccdddddbdbddbdddddddddddddddddddddddddddddddddddddddddddddddddddddddbcffffffddfffffffffffffffddffffffffffffffffffffff
    cccccccfccffffcffffffcdfffffcfddddddddddddbccbddddbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbcfffffffffdfffffffffcffffffffffffffbffffffffffffff
    ccfcccfffffffffffffffffffffcfccddddddddddbdcdddddddddddddddddddddddddddddddddddddddddddddbccbbccbcbbbdbbbdbfffdffffffffffffffffcfffffffffffffddfffffffffffffffff
    cffcccffffffffffffffffffffffbcfcdddddddddccbdbdddddddddddddddddddddddddddddddddddddddbddfccccbfcfffffcbcfffcffcffffffffffccfffcffffffffffffffdbfffffffffffffffff
    fcfffffffffffffffffffffffffffffbcbbdddddbcbcdbbbcbdbddddddddddddddddddddddddddddddbbccffffffffffffffffcbfffffffffffdffffcfffffffffffffffffffccffffffffffffffffff
    fffffffffffffffffffffffffffffffcfffcdcfffcbcfcbccfccbddddddddddddddddddddddddddddbbbcfffffffffffffffffffcdbffffffffffffcdfdfffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcffffffdffdfcffffccddddddddddddddddddddddddbdccfffffffffffffffffffffcffffcffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffdfffffbfbfffffbcfbffffffcccbcbcbdddddddddddddccccffffffffffffffffffffffffffffffffffffffffffcfffffffccfffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffccffffffffffffffdfdcfffffddffcffccccffbdbbbdddcfdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffff
    fffffffffffffffffffcffffffffffffffffffffffffffffffffddfcfbfffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffcfffffdcfffddffffffffffffffffbffffcbffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffcfffff
    ffffffffffffffffffffffdfffffffffcfffffffbffffffffffdffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbdffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffbffffdfffcddcfffffffffffffffff
    fffffffffffffffffffffffffffffffffbffffffbffffffffffffffffffffffbfcffffcfffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffdddffffffffffccffffff
    `)
Set_HP()
Set_Spell()
Set_MySprite()
info.setScore(0)
info.setLife(3)
scene.setBackgroundColor(1)
effects.starField.startScreenEffect()
BossSpawn = false
Message_spawn = true
let Just_Spawn = false
Dead = false
game.showLongText("Hogwarts in under attack! Fight Voldemort's army to protect it.", DialogLayout.Bottom)
game.onUpdate(function () {
    for (let value of sprites.allOfKind(SpriteKind.Enemy)) {
        if (value.y < 0) {
            value.destroy()
            info.changeLifeBy(-1)
        }
    }
})
game.onUpdate(function () {
    if (Voldemort_Fire_TIme <= game.runtime() && !(Voldemort_Fired)) {
        Voldemort_Spell = sprites.createProjectileFromSprite(img`
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            ....................3....................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            `, Voldemort, -100, 0)
        Voldemort_Spell.setKind(SpriteKind.Spell)
        animation.runImageAnimation(
        Voldemort_Spell,
        [CastSpell1, CastSpell2, CastSpell3, CastSpell4],
        150,
        false
        )
        Voldemort_Fired = true
    }
})
game.onUpdate(function () {
    if (ProjectileFireTime <= game.runtime() && !(Fired)) {
        Bellatrix_Spell = sprites.createProjectileFromSprite(img`
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            ....................3....................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            .........................................
            `, Bellatrix, -100, 0)
        Bellatrix_Spell.setKind(SpriteKind.Spell)
        animation.runImageAnimation(
        Bellatrix_Spell,
        [CastSpell1, CastSpell2, CastSpell3, CastSpell4],
        150,
        false
        )
        Fired = true
    }
})
game.onUpdateInterval(randint(1000, 1500), function () {
    if (Message_spawn == true && !(BossSpawn)) {
        MyEnemy_1 = sprites.createProjectileFromSide(img`
            . f f f . . . . . . . . f f f . 
            f f c . . . . . . . f c b b c . 
            f c c . . . . . . f c b b c . . 
            c f . . . . . . . f b c c c . . 
            c f f . . . . . f f b b c c . . 
            f f f c c . c c f b c b b c . . 
            f f f c c c c c f b c c b c . . 
            . f c 3 c c 3 b c b c c c . . . 
            . c b 3 b c 3 b b c c c c . . . 
            c c b b b b b b b b c c . . . . 
            c 1 1 b b b 1 1 b b b f c . . . 
            f b b b b b b b b b b f c c . . 
            f b c b b b c b b b b f . . . . 
            . f 1 f f f 1 b b b c f . . . . 
            . . f b b b b b b c f . . . . . 
            . . . f f f f f f f . . . . . . 
            `, 0, -50)
        MyEnemy_1.x = randint(51, 155)
        MyEnemy_1.setKind(SpriteKind.Enemy)
    }
})
game.onUpdateInterval(2000, function () {
    if (BossSpawn == true) {
        Voldemort_Fire_TIme = game.runtime() + randint(500, 1000)
        Voldemort_Fired = false
    }
})
game.onUpdateInterval(3100, function () {
    MakeBellatrix()
})
